/*
Modified from gl_uihotkeys.ssl
*/

#include "..\headers\sfall\sfall.h"
#include "..\headers\sfall\dik.h"

procedure start;

procedure start begin
   if game_loaded then begin
      register_hook(HOOK_KEYPRESS);
   end else begin
      variable
         event := get_sfall_arg,
         keyDX := get_sfall_arg,
         dummy;

      if (event) then begin
         if (keyDX == DIK_J) then begin
            dummy = call_offset_r0(0x4829F0);
         end
      end
   end
end
